files/script/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Laravel Default Auth Routes
Auth::routes();

// // sitemap route
Route::group(['namespace'=>'App\Http\Controllers'],function(){

	Route::get('/sitemap.xml', 'SettingController@sitemapView');
	Route::get('locale/lang', 'LocalizationController@store')->name('language.set');
	Route::get('/mysettings', 'Admin\UserController@index')->name('admin.admin.mysettings')->middleware('auth');
	Route::post('genup', 'Admin\UserController@genUpdate')->name('admin.users.genupdate')->middleware('auth');
	Route::post('passup', 'Admin\UserController@updatePassword')->name('admin.users.passup')->middleware('auth');

});


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| All Admin routes are here
|
*/

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => ['auth', 'admin']], function () {
	//dashboard route
	Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
	Route::get('static_data', 'DashboardController@static_data')->name('static_data');
	Route::get('dashboard/data/{period}', 'DashboardController@dashboardData')->name('dashboard.data');

	// role routes
	Route::resource('role', 'RoleController');
	Route::post('roles/destroy', 'RoleController@destroy')->name('roles.destroy');

	// users routes
	Route::resource('users', 'AdminController');
	Route::post('/userss/destroy', 'AdminController@destroy')->name('users.destroy');

	// page resource route
	Route::resource('page', 'PageController');
	Route::post('pages/destroy', 'PageController@destroy')->name('page.destroy');

	// blog resource route
	Route::resource('blog/post', 'PostController');
	Route::get('/blog/posts','PostController@index')->name('blog.all');
	Route::post('post/destroy', 'PostController@destroy')->name('post.destroys');
	Route::resource('blog/comment', 'CommentController');
	Route::get('/comment/disqus', 'CommentController@apiview')->name('dsiqus.settings');
	Route::post('blog/comments/destroy', 'CommentController@destroy')->name('comments.destroy');
	Route::get('blog/comments/reply/{id}', 'CommentController@reply')->name('comment.reply');

    // Disques Comment Route
	Route::post('disqus', 'CommentController@disqus')->name('disqus.store');

    // theme route
	Route::get('appearance/theme-options', 'ThemeoptionsController@index')->name('theme_option');

	// category route
	Route::post('categorys', 'CategoryController@destroy')->name('categorys.destroy');

	Route::resource('settings', 'SettingsController');
	// menu route
	Route::resource('appearance/menu', 'MenuController');
	Route::post('menues/destroy', 'MenuController@destroy')->name('menues.destroy');
	Route::post('menues/node', 'MenuController@MenuNodeStore')->name('menus.MenuNodeStore');

	//theme route
	Route::get('appearance/theme', 'ThemeController@index')->name('theme.index');
	Route::get('theme/{name}', 'ThemeController@active')->name('theme.active');
	Route::post('theme/upload', 'ThemeController@upload')->name('theme.upload');

	//widget route
	Route::get('appearance/widget', 'WidgetController@index')->name('widget.index');
	Route::get('appearance/bank/settings','WidgetController@bank_settings')->name('bank.settings');
	Route::post('appearance/bank/settings/update','WidgetController@bank_settings_update')->name('bank.settings.update');

	//themeoptions route
	Route::get('appearance/themeoptions', 'ThemeoptionsController@index')->name('themeoptions.index');

	//script route
	Route::resource('appearance/script', 'ScriptController');

	//Plugin route
	Route::get('plugin', 'PluginController@index')->name('plugin.index');
	Route::get('plugin/active/{plugin}', 'PluginController@active')->name('plugin.active');
	Route::get('plugin/deactive/{plugin}', 'PluginController@deactive')->name('plugin.deactive');
	Route::post('plugin/upload', 'PluginController@upload')->name('plugin.upload');

	//seo route
	Route::resource('setting/seo', 'SeoController');
	Route::get('setting/google-analytics', 'SettingsController@google_analytics')->name('google_analytics');
	Route::post('google_analytics_json', 'SettingsController@google_analytics_update')->name('google_analytics_service');

	//env route
	Route::resource('setting/env', 'EnvController');
	Route::resource('setting/filesystem', 'FilesystemController');

	//performance route
	Route::resource('setting/performance', 'PerfomaceController');

	//general route
	Route::resource('setting/general', 'GensettingsController');

	// permission route
	Route::get('permission', 'PermissionController@index')->name('permission.index');

	// usersystem route
	Route::get('usersystem', 'UsersystemController@index')->name('usersystem.index');

	// information route
	Route::get('information', 'InformationController@index')->name('information.index');

	//permissions Route
	Route::resource('permission', 'PermissionController');

	// Backup Route
	Route::get('backup','BackupController@index')->name('backup.index');
	Route::get('backup/store','BackupController@backup')->name('backup.store');
	Route::get('backup/delete/{file}','BackupController@delete')->name('backup.delete');
	Route::get('backup/download/{file}','BackupController@download')->name('backup.download');

	//langauge route
	Route::get('language','LanguageController@index')->name('language.index');
	Route::get('language/create','LanguageController@create')->name('language.create');
	Route::post('lang/store','LanguageController@store')->name('lang.store');
	Route::post('lang/set','LanguageController@set')->name('lang.set');
	Route::get('lang/{lang_code}/delete/{theme_name}','LanguageController@delete')->name('lang.delete');
	Route::get('lang/{lang_code}/edit/{theme_name}','LanguageController@edit')->name('lang.edit');
	Route::post('lang/{lang_code}/update/{theme_name}','LanguageController@update')->name('lang.update');

    // Media Routes
	Route::resource('media', 'MediaController');
	Route::get('medias/upload', 'MediaController@bulk_upload')->name('media.upload');
	Route::get('medias/json', 'MediaController@json')->name('medias.json');
	Route::get('media/info/{id}', 'MediaController@show');
	Route::post('medias/remove', 'MediaController@destroy')->name('medias.destroy');

	// Customizer All Route
	Route::get('customizer','CustomizerController@index')->name('customizer.index');
	Route::get('customizer/page_change','CustomizerController@page_change')->name('customizer.page_change');
	Route::get('customizer/section_option','CustomizerController@section_option')->name('customizer.section_option');
	Route::get('customizer/value_update','CustomizerController@value_update')->name('customizer.value_update');
	Route::get('customizer/multiple_settings_option','CustomizerController@multiple_settings_option')->name('customizer.multiple_settings_option');
	Route::post('customizer/image_upload','CustomizerController@image_upload')->name('customizer.image_upload');
	Route::get('customizer/save','CustomizerController@save')->name('customizer.save');
	Route::get('appearance/theme-options/settings','SettingsController@theme_settings')->name('theme.settings');
	Route::post('appearance/theme-options/settings-update','SettingsController@theme_settings_update')->name('theme.settings.update');

});


/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
|
| All Frontend routes are here
|
*/

Route::group(['namespace'=>'Amcoders\Theme\jomidar\http\controllers','middleware'=>'web'],function(){
	Route::get('/get_latest_property','DataController@get_latest_property')->name('latest.property');
	Route::get('/get_random_property','DataController@get_random_property')->name('random.property');
	Route::get('agents/data','DataController@agents')->name('agent.data');
	Route::get('recent_property/data','DataController@recent_property')->name('recent_property.data');
	Route::get('page_analytics','DataController@page_analytics');
	Route::get('city/data','DataController@city_data')->name('city.data');
	Route::get('blog/data','DataController@blog_data')->name('blog.data');
	Route::get('review/data','DataController@review')->name('review.data');
	Route::post('mailchamp','MailchampController@store')->name('mailchamp.store');
	Route::get('property/{slug}','PropertyController@show')->name('property.show');
	Route::get('project/{slug}','PropertyController@project_view');
	Route::get('list','PropertyController@list')->name('list');
	Route::get('project','PropertyController@project');
	Route::get('map','PropertyController@map')->name('map');
	Route::get('state/{slug}','PropertyController@city');
	Route::get('get_properties','DataController@get_properties');
	Route::get('get_projects','DataController@get_projects');
	Route::get('reviews','PropertyController@reviews')->name('reviews.data');
	Route::post('review/store','PropertyController@review_store')->name('review.store');
	Route::post('property/inquiryform','PropertyController@inquiryform')->name('property.inquiryform');
	Route::post('mortgage/calculator','PropertyController@calculator')->name('mortgage.calculator');
	Route::get('agent/{slug}/show','AgentshowController@show')->name('agent.show');
	Route::get('agent/property/list/{slug}','AgentshowController@property_get')->name('agent.property');
	Route::get('agent/property/review/get','AgentshowController@review_get')->name('agent.reviews.data');
	Route::get('agency/{slug}/show','AgencyController@show')->name('agency.show');

files/script/app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
     protected $table="menu";
}

files/script/app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Menu;
use App\Options;
use App\Category;
use DB;
use Auth;
use Cache;
class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        if (!Auth()->user()->can('menu')) {
            abort(401);
        }
        $file = file_get_contents( base_path().'/am-content/Themes/theme.json');
        $themes = json_decode($file, true);
        foreach ($themes as $theme) {
            if ($theme['status'] == 'active') {
                $customizer_file = file_get_contents( base_path().'/am-content/Themes/'.$theme['Text Domain'].'/customizer.json');
                $active_theme = json_decode($customizer_file,true);
                foreach ($active_theme as $key => $value) {
                    if ($value['status'] == 'active') {
                       include_once(base_path().'/am-content/Themes/'.$theme['Text Domain'].'/functions.php');

                    }
                }
            }
        }

        if (function_exists('RegisterMenu')) {
           $positions=RegisterMenu();
        }
        $positions=$positions ?? '';
        $menus= Menu::latest()->get();
        $langs=Category::where('type','lang')->get();
       
        return view('admin.menu.create',compact('menus','langs','positions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->status==1) {
            if ($request->position == 'header') {
                DB::table('menu')->where('position',$request->position)->where('lang',$request->lang)->update(['status'=>0]);
            }   
        }
        $men=new Menu;
        $men->name=$request->name;
        $men->position=$request->position;
        $men->status=$request->status;
        $men->lang=$request->lang;
        $men->data="[]";
        $men->save();


        return response()->json(['Menu Created']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         if (!Auth()->user()->can('menu')) {
            abort(401);
        }
        $info= Menu::find($id);

        return view('admin.menu.index',compact('info'));
    }
    /*
    update menus json row in  menus table
    */
    public function MenuNodeStore(Request $request)
    {
        $info= Menu::find($request->menu_id);
        $info->data=$request->data;
        $info->save();
        Cache::forget($info->position.$info->lang);
        return response()->json(['Menu Updated']);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         if (!Auth()->user()->can('menu')) {
            abort(401);
        }
         $file = file_get_contents( base_path().'/am-content/Themes/theme.json');
        $themes = json_decode($file, true);
        foreach ($themes as $theme) {
            if ($theme['status'] == 'active') {
                $customizer_file = file_get_contents( base_path().'/am-content/Themes/'.$theme['Text Domain'].'/customizer.json');
                $active_theme = json_decode($customizer_file,true);
                foreach ($active_theme as $key => $value) {
                    if ($value['status'] == 'active') {
                       include_once(base_path().'/am-content/Themes/'.$theme['Text Domain'].'/functions.php');

                    }
                }
            }
        }

        if (function_exists('RegisterMenu')) {
            $positions=RegisterMenu();
        }
        $positions=$positions ?? '';

       $langs=Category::where('type','lang')->get();
       $info= Menu::find($id);
       return view('admin.menu.edit',compact('info','langs','positions'));
      
     
   }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->status==1) {
           if ($request->position == 'header') {
            DB::table('menu')->where('position',$request->position)->where('lang',$request->lang)->update(['status'=>0]);
        }
    }

    $men= Menu::find($id);
    $men->name=$request->name;
    $men->position=$request->position;
    $men->status=$request->status;
    $men->lang=$request->lang;
    $men->save();
     Cache::forget($request->position.$request->lang);
    return response()->json(['Menu Updated']);
   }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
       if ($request->method=='delete') {
           if ($request->ids) {
            foreach ($request->ids as $id) {
               Menu::destroy($id);
           }
       }
   }

   return response()->json(['Menu Removed']);
}


}

files/script/resources/views/admin/menu/create.blade.php
@extends('layouts.backend.app')

@section('content')
<div class="row" id="category_body">
	<div class="col-lg-4">
		<div class="card">
			<div class="card-body">
				<div class="alert alert-danger none">
					<ul id="errors">
					</ul>
				</div>
				<div class="alert alert-success none">
					<ul id="success">
					</ul>
				</div>
				<form id="basicform" method="post" action="{{ route('admin.menu.store') }}">
					@csrf
					<div class="custom-form">
						<div class="form-group">
							<label for="name">{{ __('Menu Name') }}</label>
							<input type="text" name="name" class="form-control" id="name" placeholder="Menu Name">
						</div>
						<div class="form-group">
							<label for="position">{{ __('Menu Position') }}</label>
							<select class="custom-select mr-sm-2" id="position" name="position">
								@if(!empty($positions))
								@foreach($positions as $key=>$row)
								<option value="{{ $row['position'] }}">{{ $row['position'] }}</option>
								@endforeach
								@else
								<option value="header">{{ __('Header') }}</option>
								<option value="footer">{{ __('Footer') }}</option>
								@endif
							</select>
						</div>
						<div class="form-group">
							<label for="lang">{{ __('Select Language') }}</label>
							<select class="custom-select mr-sm-2" id="lang" name="lang">
								@foreach($langs as $row)
								<option value="{{ $row->slug }}">{{ $row->slug }}</option>
								@endforeach
							</select>
						</div>
						<div class="form-group">
							<label for="position">{{ __('Menu Status') }}</label>
							<select class="custom-select mr-sm-2" id="status" name="status">
								<option value="1">{{ __('Active') }}</option>
								<option value="0" selected="">{{ __('Draft') }}</option>
							</select>
						</div>
						<div class="form-group mt-20">
							<button class="btn btn-primary col-12" type="submit">{{ __('Add New Menu') }}</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="col-lg-8" >
		<div class="card">
			<div class="card-body">
				<div class="table-responsive">
					<div class="card-action-filter">
						<form id="basicform1" method="post" action="{{ route('admin.menues.destroy') }}">
							@csrf
							<div class="card-filter-content d-flex">
								<div class="single-filter">
									<div class="form-group">
										<select class="form-control selectric" name="method">
											<option >{{ __('Select Actions') }}</option>
											<option value="delete">{{ __('Delete Permanently') }}</option>
										</select>
									</div>
								</div>
								<div class="single-filter ml-1">
									<button type="submit" class="btn btn-primary btn-lg">{{ __('Apply') }}</button>
								</div>
							</div>
						</div>
						<div id="menuArea">
							<table class="table text-center category">
								<thead>
									<tr>
										<th class="am-select">
											<div class="custom-control custom-checkbox">
												<input type="checkbox" class="custom-control-input checkAll" id="checkAll">
												<label class="custom-control-label" for="checkAll"></label>
											</div>
										</th>
										<th class="am-title">{{ __('Title') }}</th>
										<th class="am-title">{{ __('Postion') }}</th>
										<th class="am-title">{{ __('Language') }}</th>
										<th class="am-title">{{ __('Status') }}</th>
										<th class="am-title">{{ __('Customize') }}</th>
										<th class="am-title">{{ __('Action') }}</th>
									</tr>
								</thead>
								<tbody>
									@foreach(App\Menu::latest()->get() as $menu)
									<td>
										<div class="custom-control custom-checkbox">
											<input type="checkbox" name="ids[]" class="custom-control-input" id="customCheck{{ $menu->id }}" value="{{ $menu->id }}">
											<label class="custom-control-label" for="customCheck{{ $menu->id }}"></label>
										</div>
									</td>
									<td>{{ $menu->name }} </td>
									<td>{{ $menu->position }}</td>
									<td>{{ $menu->lang }}</td>
									<td>@if($menu->status==1) <p class="badge badge-success">{{ __('Active Menu') }}</p> @else <p class="badge badge-danger">{{ __('Draft Menu') }}</p> @endif</td>

									<td><a href="{{ route('admin.menu.show',$menu->id) }}"><i class="fas fa-arrows-alt"></i> {{ __('Customize') }}</a></td>
									<td><a  class="text-success" href="{{ route('admin.menu.edit',$menu->id) }}" ><i class="far fa-edit"></i></a></td>
								</tr>
								@endforeach
							</tbody>
						</form>
						<tfoot>
							<tr>
								<th class="am-select">
									<div class="custom-control custom-checkbox">
										<input type="checkbox" class="custom-control-input checkAll" id="checkAll">
										<label class="custom-control-label" for="checkAll"></label>
									</div>
								</th>
								<th class="am-title">{{ __('Title') }}</th>
								<th class="am-author">{{ __('Postion') }}</th>
								<th class="am-title">{{ __('Language') }}</th>
								<th class="am-author">{{ __('Status') }}</th>
								<th class="am-title">{{ __('Customize') }}</th>
								<th class="am-author">{{ __('Action') }}</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script>
	"use strict";
	//success response will assign this function
	function success(res){
		$('#menuArea').load(' #menuArea');
		Sweet('success','Menu Creaed')
	}

	$(".checkAll").on('click',function(){
		$('input:checkbox').not(this).prop('checked', this.checked);
	});
</script>
@endsection

files/script/resources/views/admin/menu/edit.blade.php
@extends('layouts.backend.app')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-body">
				<h4 class="mb-20">{{ __('Edit Menu') }}</h4>
				<div class="row">
					<div class="col-lg-12">
						<div class="alert alert-danger none errorarea">
							<ul id="errors">

							</ul>
						</div>
						<form method="post" id="basicform" action="{{ route('admin.menu.update',$info->id) }}">
							@csrf
							@method('PUT')
							<div class="custom-form">
								<div class="form-group">
									<label for="name">{{ __('Menu Name') }}</label>
									<input type="text" name="name" class="form-control" id="name" value="{{ $info->name }}">
								</div>
								<div class="form-group">
									<label for="position">{{ __('Menu Position') }}</label>
									<select class="custom-select mr-sm-2" id="position" name="position">
										@if(!empty($positions))
										@foreach($positions as $key=>$row)
										<option value="{{ $row['position'] }}" @if($info->position == $row['position']) selected="" @endif>{{ $row['position'] }}</option>
										@endforeach
										@else
										<option value="header" @if($info->position=='header') selected="" @endif>{{ __('Header') }}</option>
										<option value="footer" @if($info->position=='footer') selected="" @endif>{{ __('Footer') }}</option>
										@endif
									</select>
								</div>
								<div class="form-group">
									<label for="lang">{{ __('Select Language') }}</label>
									<select class="custom-select mr-sm-2" id="lang" name="lang">
										@foreach($langs as $row)
										<option value="{{ $row->slug }}" @if($info->lang== $row->slug) selected="" @endif>{{ $row->slug }}</option>
										@endforeach
									</select>
								</div>
								<div class="form-group">
									<label for="position">{{ __('Menu Status') }}</label>
									<select class="custom-select mr-sm-2" id="status" name="status">
										<option value="1" @if($info->status==1) selected="" @endif>{{ __('Active') }}</option>
										<option value="0"  @if($info->status==0) selected="" @endif>{{ __('Draft') }}</option>
									</select>
								</div>
								<button class="btn  btn-primary col-12 mt-10">{{ __('Update') }}</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script>
	"use strict";
	//success response will assign this function
	function success(res){
		$('.alert-danger').hide();

	}
	function errosresponse(xhr){
		$('.alert-success').hide();
		$('.alert-danger').show();

	}
</script>
@endsection

files/script/resources/views/admin/menu/index.blade.php
@extends('layouts.backend.app')

@section('style')
<link rel="stylesheet" href="{{ asset('admin/bootstrap-iconpicker/css/bootstrap-iconpicker.min.css') }}"/>
@endsection

@section('content')
<div class="row">
	<div class="col-md-4">
		<div class="card">
			<div class="card-body">
				<h4 class="mb-20">{{ __('Menu List') }}</h4>
				<div class="row">
					<div class="col-lg-12">
						<div class="alert alert-danger none">
							<ul id="errors"></ul>
						</div>
						<form id="frmEdit" class="form-horizontal">
							<div class="custom-form">
								<div class="form-group">
									<label for="text">{{ __('Text') }}</label>
									<div class="input-group">
										<input type="text" class="form-control item-menu" name="text" id="text" placeholder="Text" autocomplete="off">
										<div class="input-group-append">
											<button type="button" id="myEditor_icon" class="btn btn-primary btn-sm"></button>
										</div>
									</div>
									<input type="hidden" name="icon" class="item-menu">
								</div>
								<div class="form-group">
									<label for="href">{{ __('URL') }}</label>
									<input type="text" class="form-control item-menu" id="href" name="href" placeholder="URL" required autocomplete="off">
								</div>
								<div class="form-group">
									<label for="target">{{ __('Target') }}</label>
									<select name="target" id="target" class="custom-select mr-sm-2 item-menu">
										<option value="_self">{{ __('Self') }}</option>
										<option value="_blank">{{ __('Blank') }}</option>
										<option value="_top">{{ __('Top') }}</option>
									</select>
								</div>
								<div class="form-group none">
									<label for="title">{{ __('Tooltip') }}</label>
									<input type="text" name="title" class="form-control item-menu" id="title" placeholder="Tooltip">
								</div>
							</div>
						</form>
						<div class="menu-add-update d-flex">
							<button type="button" id="btnUpdate" class="btn btn-update  btn-warning text-white col-6 mr-2" disabled><i class="fas fa-sync-alt"></i> {{ __('Update') }}</button>
							<button type="button" id="btnAdd" class="btn btn-success col-6 "><i class="fas fa-plus"></i> {{ __('Add') }}</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-8">
		<div class="card mb-3">
			<div class="card-body">
				<div class="row mb-10" style="align-items: center;">
					<div class="col-lg-6">
						<h4>{{ __('Menu structure') }}</h4>
					</div>
					<div class="col-lg-6">
						<div class="save-menu float-right" >
							<form id="basicform" class="float-right" method="post" action="{{ route('admin.menus.MenuNodeStore') }}"> @csrf <input type="hidden" name="data" id="data"> <input type="hidden" name="menu_id" value="{{ $info->id }}"> <button id="form-button" class="btn btn-primary " type="submit">{{ __('Save Changes') }}</button></form>
						</div>
					</div>
				</div>
				<ul id="myEditor" class="sortableLists list-group">
				</ul>

			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
<script  src="{{ asset('admin/js/bootstrap.bundle.min.js') }}"></script>
<script  src="{{ asset('admin/js/jquery-menu-editor.min.js') }}"></script>
<script  src="{{ asset('admin/bootstrap-iconpicker/js/iconset/fontawesome5-3-1.min.js') }}"></script>
<script  src="{{ asset('admin/bootstrap-iconpicker/js/bootstrap-iconpicker.min.js') }}"></script>
<script src="{{ asset('admin/js/form.js') }}"></script>
<script>
"use strict";
(function ($) {
    // menu items
    var arrayjson = {!! $info->data !!};
    // icon picker options
    var iconPickerOptions = {searchText: "Search...", labelHeader: "{0}/{1}"};
    // sortable list options
    var sortableListOptions = {
    	placeholderCss: {'background-color': "#cccccc"}
    };

    var editor = new MenuEditor('myEditor', {listOptions: sortableListOptions, iconPicker: iconPickerOptions});
    editor.setForm($('#frmEdit'));
    editor.setUpdateButton($('#btnUpdate'));
    $('#btnReload').on('click', function () {
    	editor.setData(arrayjson);
    });

    $('#btnOutput').on('click', function () {
    	var str = editor.getString();
    	$("#out").text(str);
    });

    $("#btnUpdate").on('click',function(){
    	if ($('#text').val() != '' && $('#href').val() != '') {
    		editor.update();
    	}
    });

    $('#btnAdd').on('click',function(){
    	if ($('#text').val() != '' && $('#href').val() != '') {
    		editor.add();
    	}

    });

    $('#form-button').on('click',function(){
    	$("#data").val(editor.getString());
    })
    editor.setData(arrayjson);
})(jQuery);
function success(res){
    $('.alert-danger').hide();
    $('.alert-success').show();
    $("#success").html("<li class='text-success'>"+res+"</li>");
}
function errosresponse(xhr){
    $('.alert-success').hide();
    $('.alert-danger').show();

}
</script>
@endsection