files/script/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Laravel Default Auth Routes
Auth::routes();

// // sitemap route
Route::group(['namespace'=>'App\Http\Controllers'],function(){

	Route::get('/sitemap.xml', 'SettingController@sitemapView');
	Route::get('locale/lang', 'LocalizationController@store')->name('language.set');
	Route::get('/mysettings', 'Admin\UserController@index')->name('admin.admin.mysettings')->middleware('auth');
	Route::post('genup', 'Admin\UserController@genUpdate')->name('admin.users.genupdate')->middleware('auth');
	Route::post('passup', 'Admin\UserController@updatePassword')->name('admin.users.passup')->middleware('auth');

});


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| All Admin routes are here
|
*/

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => ['auth', 'admin']], function () {
	//dashboard route
	Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
	Route::get('static_data', 'DashboardController@static_data')->name('static_data');
	Route::get('dashboard/data/{period}', 'DashboardController@dashboardData')->name('dashboard.data');

	// role routes
	Route::resource('role', 'RoleController');
	Route::post('roles/destroy', 'RoleController@destroy')->name('roles.destroy');

	// users routes
	Route::resource('users', 'AdminController');
	Route::post('/userss/destroy', 'AdminController@destroy')->name('users.destroy');

	// page resource route
	Route::resource('page', 'PageController');
	Route::post('pages/destroy', 'PageController@destroy')->name('page.destroy');

	// blog resource route
	Route::resource('blog/post', 'PostController');
	Route::get('/blog/posts','PostController@index')->name('blog.all');
	Route::post('post/destroy', 'PostController@destroy')->name('post.destroys');
	Route::resource('blog/comment', 'CommentController');
	Route::get('/comment/disqus', 'CommentController@apiview')->name('dsiqus.settings');
	Route::post('blog/comments/destroy', 'CommentController@destroy')->name('comments.destroy');
	Route::get('blog/comments/reply/{id}', 'CommentController@reply')->name('comment.reply');

    // Disques Comment Route
	Route::post('disqus', 'CommentController@disqus')->name('disqus.store');

    // theme route
	Route::get('appearance/theme-options', 'ThemeoptionsController@index')->name('theme_option');

	// category route
	Route::post('categorys', 'CategoryController@destroy')->name('categorys.destroy');

	Route::resource('settings', 'SettingsController');
	// menu route
	Route::resource('appearance/menu', 'MenuController');
	Route::post('menues/destroy', 'MenuController@destroy')->name('menues.destroy');
	Route::post('menues/node', 'MenuController@MenuNodeStore')->name('menus.MenuNodeStore');

	//theme route
	Route::get('appearance/theme', 'ThemeController@index')->name('theme.index');
	Route::get('theme/{name}', 'ThemeController@active')->name('theme.active');
	Route::post('theme/upload', 'ThemeController@upload')->name('theme.upload');

	//widget route
	Route::get('appearance/widget', 'WidgetController@index')->name('widget.index');
	Route::get('appearance/bank/settings','WidgetController@bank_settings')->name('bank.settings');
	Route::post('appearance/bank/settings/update','WidgetController@bank_settings_update')->name('bank.settings.update');

	//themeoptions route
	Route::get('appearance/themeoptions', 'ThemeoptionsController@index')->name('themeoptions.index');

	//script route
	Route::resource('appearance/script', 'ScriptController');

	//Plugin route
	Route::get('plugin', 'PluginController@index')->name('plugin.index');
	Route::get('plugin/active/{plugin}', 'PluginController@active')->name('plugin.active');
	Route::get('plugin/deactive/{plugin}', 'PluginController@deactive')->name('plugin.deactive');
	Route::post('plugin/upload', 'PluginController@upload')->name('plugin.upload');

	//seo route
	Route::resource('setting/seo', 'SeoController');
	Route::get('setting/google-analytics', 'SettingsController@google_analytics')->name('google_analytics');
	Route::post('google_analytics_json', 'SettingsController@google_analytics_update')->name('google_analytics_service');

	//env route
	Route::resource('setting/env', 'EnvController');
	Route::resource('setting/filesystem', 'FilesystemController');

	//performance route
	Route::resource('setting/performance', 'PerfomaceController');

	//general route
	Route::resource('setting/general', 'GensettingsController');

	// permission route
	Route::get('permission', 'PermissionController@index')->name('permission.index');

	// usersystem route
	Route::get('usersystem', 'UsersystemController@index')->name('usersystem.index');

	// information route
	Route::get('information', 'InformationController@index')->name('information.index');

	//permissions Route
	Route::resource('permission', 'PermissionController');

	// Backup Route
	Route::get('backup','BackupController@index')->name('backup.index');
	Route::get('backup/store','BackupController@backup')->name('backup.store');
	Route::get('backup/delete/{file}','BackupController@delete')->name('backup.delete');
	Route::get('backup/download/{file}','BackupController@download')->name('backup.download');

	//langauge route
	Route::get('language','LanguageController@index')->name('language.index');
	Route::get('language/create','LanguageController@create')->name('language.create');
	Route::post('lang/store','LanguageController@store')->name('lang.store');
	Route::post('lang/set','LanguageController@set')->name('lang.set');
	Route::get('lang/{lang_code}/delete/{theme_name}','LanguageController@delete')->name('lang.delete');
	Route::get('lang/{lang_code}/edit/{theme_name}','LanguageController@edit')->name('lang.edit');
	Route::post('lang/{lang_code}/update/{theme_name}','LanguageController@update')->name('lang.update');

    // Media Routes
	Route::resource('media', 'MediaController');
	Route::get('medias/upload', 'MediaController@bulk_upload')->name('media.upload');
	Route::get('medias/json', 'MediaController@json')->name('medias.json');
	Route::get('media/info/{id}', 'MediaController@show');
	Route::post('medias/remove', 'MediaController@destroy')->name('medias.destroy');

	// Customizer All Route
	Route::get('customizer','CustomizerController@index')->name('customizer.index');
	Route::get('customizer/page_change','CustomizerController@page_change')->name('customizer.page_change');
	Route::get('customizer/section_option','CustomizerController@section_option')->name('customizer.section_option');
	Route::get('customizer/value_update','CustomizerController@value_update')->name('customizer.value_update');
	Route::get('customizer/multiple_settings_option','CustomizerController@multiple_settings_option')->name('customizer.multiple_settings_option');
	Route::post('customizer/image_upload','CustomizerController@image_upload')->name('customizer.image_upload');
	Route::get('customizer/save','CustomizerController@save')->name('customizer.save');
	Route::get('appearance/theme-options/settings','SettingsController@theme_settings')->name('theme.settings');
	Route::post('appearance/theme-options/settings-update','SettingsController@theme_settings_update')->name('theme.settings.update');

});


/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
|
| All Frontend routes are here
|
*/

Route::group(['namespace'=>'Amcoders\Theme\jomidar\http\controllers','middleware'=>'web'],function(){
	Route::get('/get_latest_property','DataController@get_latest_property')->name('latest.property');
	Route::get('/get_random_property','DataController@get_random_property')->name('random.property');
	Route::get('agents/data','DataController@agents')->name('agent.data');
	Route::get('recent_property/data','DataController@recent_property')->name('recent_property.data');
	Route::get('page_analytics','DataController@page_analytics');
	Route::get('city/data','DataController@city_data')->name('city.data');
	Route::get('blog/data','DataController@blog_data')->name('blog.data');
	Route::get('review/data','DataController@review')->name('review.data');
	Route::post('mailchamp','MailchampController@store')->name('mailchamp.store');
	Route::get('property/{slug}','PropertyController@show')->name('property.show');
	Route::get('project/{slug}','PropertyController@project_view');
	Route::get('list','PropertyController@list')->name('list');
	Route::get('project','PropertyController@project');
	Route::get('map','PropertyController@map')->name('map');
	Route::get('state/{slug}','PropertyController@city');
	Route::get('get_properties','DataController@get_properties');
	Route::get('get_projects','DataController@get_projects');
	Route::get('reviews','PropertyController@reviews')->name('reviews.data');
	Route::post('review/store','PropertyController@review_store')->name('review.store');
	Route::post('property/inquiryform','PropertyController@inquiryform')->name('property.inquiryform');
	Route::post('mortgage/calculator','PropertyController@calculator')->name('mortgage.calculator');
	Route::get('agent/{slug}/show','AgentshowController@show')->name('agent.show');
	Route::get('agent/property/list/{slug}','AgentshowController@property_get')->name('agent.property');
	Route::get('agent/property/review/get','AgentshowController@review_get')->name('agent.reviews.data');
	Route::get('agency/{slug}/show','AgencyController@show')->name('agency.show');

files/script/app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\Options;
use File;
class SettingsController extends Controller
{
    public function google_analytics(){
        return view('admin.settings.google_analytics');
    }

    public function google_analytics_update(Request $request){
        if ($request->file) {
           $path='uploads/';
           $fileName = 'service-account-credentials.'.$request->file->extension();
           $request->file->move($path,$fileName);
       }

       return response()->json(['Service Account Updated']);
    }

   
    public function theme_settings()
    {
      
    	$info=Options::where('key','theme_data')->first();
    	$info=json_decode($info->value);
    	return view('admin.theme.theme_settings',compact('info'));
    }

    public function theme_settings_update(Request $request)
    {
    	$validatedData = $request->validate([
    		'logo' => 'max:1000|mimes:png',
    		'favicon' => 'max:100|mimes:ico',
    	]);

    	if ($request->logo) {
    		 $request->logo->move('uploads', 'logo.png'); 
    	}

    	if ($request->favicon) {
    		 $request->favicon->move('uploads', 'favicon.ico'); 
    	}
    	$links=[];
    	foreach ($request->icon as $key => $value) {
    		$data['icon']=$value;
    		$data['url']=$request->url[$key];
    		array_push($links, $data);
    	}

    	$content['theme_color']=$request->color;
    	$content['socials']=$links;
    	$content['back_to_top']=$request->back_to_top;

    	$color=Options::where('key','theme_data')->first();
    	$color->value=json_encode($content);
    	$color->save();

    	return response()->json(['Settings Updated']);
    }
}

files/script/app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Post;
use App\Page;
use App\Category;
use samdark\sitemap\Sitemap;
use samdark\sitemap\Index;
class SettingController extends Controller
{
	public function sitemapstore()
	{
		
		$index = new Index(base_path('sitemap.xml'));
		 foreach (Post::get() as  $post) {
            $url=url('/').'/post/'.$post->slug;
            $index->addSitemap($url,time(), Sitemap::DAILY, 0.3);       
        }
        foreach (Page::get() as  $post) {
            $url=url('/').'/page/'.$post->slug;
            $index->addSitemap($url,time(), Sitemap::DAILY, 0.3);       
        }
        foreach (Category::get() as  $page) {
            $url=url('/').'/category/'.$page->slug;
            $index->addSitemap($url,time(), Sitemap::DAILY, 0.3);       
        }
		$index->write();		
	}
	public function sitemapView()
	{
		
		return response(file_get_contents(base_path('sitemap.xml')), 200, [
    		'Content-Type' => 'application/xml'
		]);
	}
}

files/script/resources/views/admin/settings/google_analytics.blade.php
@extends('layouts.backend.app')
@section('content')
@include('layouts.backend.partials.headersection',['title'=>'Google analytics'])
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4>{{ __('Google Analytics') }}</h4><br>
      </div>
      <div class="card-body">
        <form class="basicform" action="{{ route('admin.google_analytics_service') }}" enctype="multipart/form-data" method="post">
          @csrf
            <input type="hidden" name="type" value="google-analytics">
            <div class="form-group row mb-4">
                <a href="{{ url('/admin/setting/env') }}" class="col-form-label text-md-right col-12 col-md-3 col-lg-3 text-primary" >{{ __('ANALYTICS_VIEW_ID') }}</a>
                <div class="col-sm-12 col-md-7">
                    <input type="text" disabled class="form-control" value="{{ env('ANALYTICS_VIEW_ID') }}">
                </div>
            </div>
            <div class="form-group row mb-4">
                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 text-primary" >{{ __('service-account-credentials.json') }}</label>
                <div class="col-sm-12 col-md-7">
                    <input type="file" name="file" class="form-control" accept=".json">
                </div>
            </div>
            <div class="form-group row mb-4">
                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                <div class="col-sm-12 col-md-7">
                    <button class="btn btn-primary basicbtn" type="submit">{{ __('Upload') }}</button><br>
                </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection
@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
@endsection

files/script/resources/views/admin/settings/my_settings.blade.php
@extends('layouts.backend.app')

@section('content')
<div class="card">
    <div class="card-body">
       <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger none">
              <ul id="errors">

              </ul>
            </div>
            <div class="alert alert-success none">
                    <ul id="success">

                    </ul>
                </div>
            </div>
            <div class="col-md-6">
                <form method="post" id="basicform" enctype="multipart/form-data" action="{{ route('admin.users.genupdate') }}">
                    @csrf
                    <h4 class="mb-20">{{ __('Edit Genaral Settings') }}</h4>
                    <div class="custom-form">
                        <div class="form-group">
                            <label for="name">{{ __('Name') }}</label>
                            <input type="text" name="name" id="name" class="form-control" required placeholder="Enter User's  Name" value="{{ $info->name }}">
                        </div>
                        <div class="form-group">
                            <label for="email">{{ __('Email') }}</label>
                            <input type="text" name="email" id="email" class="form-control" required placeholder="Enter Email"  value="{{ $info->email }}">
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-info">{{ __('Update') }}</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <form method="post" id="basicform1" action="{{ route('admin.users.passup') }}">
                    @csrf
                    <h4 class="mb-20">{{ __('Change Password') }}</h4>
                    <div class="custom-form">
                        <div class="form-group">
                            <label for="oldpassword">{{ __('Old Password') }}</label>
                            <input type="password" name="current" id="oldpassword" class="form-control"  placeholder="Enter Old Password" required>
                        </div>
                        <div class="form-group">
                            <label for="password">{{ __('New Password') }}</label>
                            <input type="password" name="password" id="password" class="form-control"  placeholder="Enter New Password" required>
                        </div>
                        <div class="form-group">
                            <label for="password1">{{ __('Enter Again Password') }}</label>
                            <input type="password" name="password_confirmation" id="password1" class="form-control"  placeholder="Enter Again" required>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{{ __('Change') }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script type="text/javascript">
    "use strict";
    function success(res){
        $('.alert-danger').hide();
        $('.alert-success').show();
        $("#success").html("<li class='text-white'>"+res+"</li>");
    }
    function errosresponse(xhr){
        $('.alert-success').hide();
        $('.alert-danger').show();
        $('#errors').append("<li class='text-white'>"+xhr.responseJSON.message+"</li>")

    }
</script>
@endsection