files/script/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Laravel Default Auth Routes
Auth::routes();

// // sitemap route
Route::group(['namespace'=>'App\Http\Controllers'],function(){

	Route::get('/sitemap.xml', 'SettingController@sitemapView');
	Route::get('locale/lang', 'LocalizationController@store')->name('language.set');
	Route::get('/mysettings', 'Admin\UserController@index')->name('admin.admin.mysettings')->middleware('auth');
	Route::post('genup', 'Admin\UserController@genUpdate')->name('admin.users.genupdate')->middleware('auth');
	Route::post('passup', 'Admin\UserController@updatePassword')->name('admin.users.passup')->middleware('auth');

});


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| All Admin routes are here
|
*/

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => ['auth', 'admin']], function () {
	//dashboard route
	Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
	Route::get('static_data', 'DashboardController@static_data')->name('static_data');
	Route::get('dashboard/data/{period}', 'DashboardController@dashboardData')->name('dashboard.data');

	// role routes
	Route::resource('role', 'RoleController');
	Route::post('roles/destroy', 'RoleController@destroy')->name('roles.destroy');

	// users routes
	Route::resource('users', 'AdminController');
	Route::post('/userss/destroy', 'AdminController@destroy')->name('users.destroy');

	// page resource route
	Route::resource('page', 'PageController');
	Route::post('pages/destroy', 'PageController@destroy')->name('page.destroy');

	// blog resource route
	Route::resource('blog/post', 'PostController');
	Route::get('/blog/posts','PostController@index')->name('blog.all');
	Route::post('post/destroy', 'PostController@destroy')->name('post.destroys');
	Route::resource('blog/comment', 'CommentController');
	Route::get('/comment/disqus', 'CommentController@apiview')->name('dsiqus.settings');
	Route::post('blog/comments/destroy', 'CommentController@destroy')->name('comments.destroy');
	Route::get('blog/comments/reply/{id}', 'CommentController@reply')->name('comment.reply');

    // Disques Comment Route
	Route::post('disqus', 'CommentController@disqus')->name('disqus.store');

    // theme route
	Route::get('appearance/theme-options', 'ThemeoptionsController@index')->name('theme_option');

	// category route
	Route::post('categorys', 'CategoryController@destroy')->name('categorys.destroy');

	Route::resource('settings', 'SettingsController');
	// menu route
	Route::resource('appearance/menu', 'MenuController');
	Route::post('menues/destroy', 'MenuController@destroy')->name('menues.destroy');
	Route::post('menues/node', 'MenuController@MenuNodeStore')->name('menus.MenuNodeStore');

	//theme route
	Route::get('appearance/theme', 'ThemeController@index')->name('theme.index');
	Route::get('theme/{name}', 'ThemeController@active')->name('theme.active');
	Route::post('theme/upload', 'ThemeController@upload')->name('theme.upload');

	//widget route
	Route::get('appearance/widget', 'WidgetController@index')->name('widget.index');
	Route::get('appearance/bank/settings','WidgetController@bank_settings')->name('bank.settings');
	Route::post('appearance/bank/settings/update','WidgetController@bank_settings_update')->name('bank.settings.update');

	//themeoptions route
	Route::get('appearance/themeoptions', 'ThemeoptionsController@index')->name('themeoptions.index');

	//script route
	Route::resource('appearance/script', 'ScriptController');

	//Plugin route
	Route::get('plugin', 'PluginController@index')->name('plugin.index');
	Route::get('plugin/active/{plugin}', 'PluginController@active')->name('plugin.active');
	Route::get('plugin/deactive/{plugin}', 'PluginController@deactive')->name('plugin.deactive');
	Route::post('plugin/upload', 'PluginController@upload')->name('plugin.upload');

	//seo route
	Route::resource('setting/seo', 'SeoController');
	Route::get('setting/google-analytics', 'SettingsController@google_analytics')->name('google_analytics');
	Route::post('google_analytics_json', 'SettingsController@google_analytics_update')->name('google_analytics_service');

	//env route
	Route::resource('setting/env', 'EnvController');
	Route::resource('setting/filesystem', 'FilesystemController');

	//performance route
	Route::resource('setting/performance', 'PerfomaceController');

	//general route
	Route::resource('setting/general', 'GensettingsController');

	// permission route
	Route::get('permission', 'PermissionController@index')->name('permission.index');

	// usersystem route
	Route::get('usersystem', 'UsersystemController@index')->name('usersystem.index');

	// information route
	Route::get('information', 'InformationController@index')->name('information.index');

	//permissions Route
	Route::resource('permission', 'PermissionController');

	// Backup Route
	Route::get('backup','BackupController@index')->name('backup.index');
	Route::get('backup/store','BackupController@backup')->name('backup.store');
	Route::get('backup/delete/{file}','BackupController@delete')->name('backup.delete');
	Route::get('backup/download/{file}','BackupController@download')->name('backup.download');

	//langauge route
	Route::get('language','LanguageController@index')->name('language.index');
	Route::get('language/create','LanguageController@create')->name('language.create');
	Route::post('lang/store','LanguageController@store')->name('lang.store');
	Route::post('lang/set','LanguageController@set')->name('lang.set');
	Route::get('lang/{lang_code}/delete/{theme_name}','LanguageController@delete')->name('lang.delete');
	Route::get('lang/{lang_code}/edit/{theme_name}','LanguageController@edit')->name('lang.edit');
	Route::post('lang/{lang_code}/update/{theme_name}','LanguageController@update')->name('lang.update');

    // Media Routes
	Route::resource('media', 'MediaController');
	Route::get('medias/upload', 'MediaController@bulk_upload')->name('media.upload');
	Route::get('medias/json', 'MediaController@json')->name('medias.json');
	Route::get('media/info/{id}', 'MediaController@show');
	Route::post('medias/remove', 'MediaController@destroy')->name('medias.destroy');

	// Customizer All Route
	Route::get('customizer','CustomizerController@index')->name('customizer.index');
	Route::get('customizer/page_change','CustomizerController@page_change')->name('customizer.page_change');
	Route::get('customizer/section_option','CustomizerController@section_option')->name('customizer.section_option');
	Route::get('customizer/value_update','CustomizerController@value_update')->name('customizer.value_update');
	Route::get('customizer/multiple_settings_option','CustomizerController@multiple_settings_option')->name('customizer.multiple_settings_option');
	Route::post('customizer/image_upload','CustomizerController@image_upload')->name('customizer.image_upload');
	Route::get('customizer/save','CustomizerController@save')->name('customizer.save');
	Route::get('appearance/theme-options/settings','SettingsController@theme_settings')->name('theme.settings');
	Route::post('appearance/theme-options/settings-update','SettingsController@theme_settings_update')->name('theme.settings.update');

});


/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
|
| All Frontend routes are here
|
*/

Route::group(['namespace'=>'Amcoders\Theme\jomidar\http\controllers','middleware'=>'web'],function(){
	Route::get('/get_latest_property','DataController@get_latest_property')->name('latest.property');
	Route::get('/get_random_property','DataController@get_random_property')->name('random.property');
	Route::get('agents/data','DataController@agents')->name('agent.data');
	Route::get('recent_property/data','DataController@recent_property')->name('recent_property.data');
	Route::get('page_analytics','DataController@page_analytics');
	Route::get('city/data','DataController@city_data')->name('city.data');
	Route::get('blog/data','DataController@blog_data')->name('blog.data');
	Route::get('review/data','DataController@review')->name('review.data');
	Route::post('mailchamp','MailchampController@store')->name('mailchamp.store');
	Route::get('property/{slug}','PropertyController@show')->name('property.show');
	Route::get('project/{slug}','PropertyController@project_view');
	Route::get('list','PropertyController@list')->name('list');
	Route::get('project','PropertyController@project');
	Route::get('map','PropertyController@map')->name('map');
	Route::get('state/{slug}','PropertyController@city');
	Route::get('get_properties','DataController@get_properties');
	Route::get('get_projects','DataController@get_projects');
	Route::get('reviews','PropertyController@reviews')->name('reviews.data');
	Route::post('review/store','PropertyController@review_store')->name('review.store');
	Route::post('property/inquiryform','PropertyController@inquiryform')->name('property.inquiryform');
	Route::post('mortgage/calculator','PropertyController@calculator')->name('mortgage.calculator');
	Route::get('agent/{slug}/show','AgentshowController@show')->name('agent.show');
	Route::get('agent/property/list/{slug}','AgentshowController@property_get')->name('agent.property');
	Route::get('agent/property/review/get','AgentshowController@review_get')->name('agent.reviews.data');
	Route::get('agency/{slug}/show','AgencyController@show')->name('agency.show');

files/script/resources/views/admin/language/create.blade.php
@extends('layouts.backend.app')

@section('style')
<link rel="stylesheet" href="{{ asset('admin/assets/css/selectric.css') }}">
@endsection

@section('content')
<div class="card">
	<div class="card-header">
		<h5>{{ __('Create New Language') }}</h5>
	</div>
	<div class="card-body">
		<form action="{{ route('admin.lang.store') }}" method="POST" id="basicform">
			@csrf
			<div class="form-group">
				<label>{{ __('Select Language') }}</label>
				<select name="language_code" class="form-control selectric">
					@foreach($countries as $row)
					<option value="{{ $row['code'] }}">{{ $row['name'] }}  -- {{ $row['nativeName'] }} -- ( {{ $row['code'] }})</option>
					@endforeach
				</select>
			</div>
			<div class="form-group">
				<label>{{ __('Select Theme') }}</label>
				<select name="theme_name" class="form-control selectric">
					@foreach ($themes as $theme)
					<option value="{{ $theme['Text Domain'] }}">{{ $theme['Theme Name'] }}</option>
					@endforeach
				</select>
			</div>
			<div class="form-group">
				<label>{{ __('Select Position') }}</label>
				<select name="theme_position" class="form-control selectric">
					<option value="LTR">{{ __('LTR') }}</option>
					<option value="RTL">{{ __('RTL') }}</option>
				</select>
			</div>
			<button type="submit" class="btn btn-primary btn-lg">{{ __('Submit') }}</button>
		</form>
	</div>
</div>
@endsection

@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script src="{{ asset('admin/assets/js/jquery.selectric.min.js') }}"></script>
<script>
	"use strict";
	//success response will assign this function
	function success(res){
		window.history.pushState('', '', '{{ route('admin.language.index') }}');
		location.reload();
	}
	function errosresponse(xhr){

		$("#errors").html("<li class='text-danger'>"+xhr.responseJSON[0]+"</li>")
	}
</script>
@endsection

files/script/resources/views/admin/language/edit.blade.php
@extends('layouts.backend.app')

@section('style')
<link rel="stylesheet" href="{{ asset('admin/assets/css/selectric.css') }}">
@endsection

@section('content')
<section class="section">
    <div class="section-header">
      <h1>{{ __('Customize Language') }}</h1>
    </div>
    <div class="section-body">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{ __('Customize Language') }}</h6>
            </div>
            <div class="card-body">
                <div class="table_append">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">{{ __('Key') }}</th>
                            <th scope="col">{{ __('Value') }}</th>
                            <th scope="col">{{ __('Action') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach($langs as $key=>$lang)
                            <tr>
                                <td>{{ $key }}</td>
                                <td>
                                    {{ $lang }}
                                </td>
                                <td><a href="#" class="btn btn-info"  data-toggle="modal" data-target="#lang_model_{{ Str::slug($lang) }}">{{ __('Edit') }}</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@section('extra')
@foreach($langs as $key=>$lang)
<div class="modal fade langmodel" id="lang_model_{{ Str::slug($lang) }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{{ __('Edit Value') }}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{ route('admin.lang.update',['lang_code'=>$id,'theme_name'=>$theme_name]) }}" method="POST" class="langform basicform">
            @csrf
            <div class="modal-body">
                <div class="form-group">
                <label for="message-text" class="col-form-label">{{ __('Value') }}:</label>
                <textarea class="form-control text-lg" name="value">{{ $lang }}</textarea>
                </div>
            </div>
            <input type="hidden" name="key" value="{{ $key }}">
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Close') }}</button>
            <button type="submit" class="btn btn-primary">{{ __('Update') }}</button>
            </div>
        </form>
      </div>
    </div>
  </div>
@endforeach
@endsection
@endsection

@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script>
    "use strict";
    function success(res){
        $('.langmodel').modal('hide');
        $('.table_append').load(' .table_append');
    }
    function errosresponse(xhr){
        $('.alert-success').hide();
        $('.alert-danger').show();
        $('#errors').append("<li class='text-white'>"+xhr.responseJSON.message+"</li>")

    }
</script>
@endsection

files/script/resources/views/admin/language/index.blade.php
@section('style')

@endsection
@extends('layouts.backend.app')

@section('content')
<div class="card shadow mb-4">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">{{ __('Manage Language') }}</h6>
	</div>
	<div class="card-body">
		<form action="{{ route('admin.lang.set') }}" method="POST" id="basicform">
			@csrf
			<div class="row">
				<div class="col-lg-3">
					<div class="form-group">
						<select name="status" class="form-control">
							<option disabled selected>{{ __('Select Option') }}</option>
							<option value="active">{{ __('Active Language') }}</option>
						</select>
					</div>
				</div>
				<input type="hidden" value="{{ $theme_name }}" name="theme_name">
				<div class="col-lg-2 pl-0">
					<button type="submit" class="btn btn-primary btn-lg">{{ __('Submit') }}</button>
				</div>
				<div class="col-lg-7">
					<a href="{{ route('admin.language.create') }}" class="btn btn-info float-right btn-lg">{{ __('Add New Language') }}</a>
				</div>
			</div>
			<table class="table table-bordered">
				<thead>
				<tr>
					<th scope="col">
						<div class="custom-control custom-checkbox">
							<input type="checkbox" class="custom-control-input checkAll" id="customCheck12">
							<label class="custom-control-label checkAll" for="customCheck12"></label>
						</div>
					</th>
					<th scope="col">{{ __('Language Name') }}</th>
					<th scope="col">{{ __('Position') }}</th>
					<th scope="col">{{ __('Theme Name') }}</th>
					<th scope="col">{{ __('Action') }}</th>
				</tr>
				</thead>
				<tbody>
					@foreach($langs as $lang)
					<tr>
						<th scope="row">
							<div class="custom-control custom-checkbox">
								<input type="checkbox" name="lang[]" {{ $lang->status == 1 ? 'checked' : '' }} class="custom-control-input" id="customCheck{{ $lang->slug }}" value="{{ $lang->slug }}">
								<label class="custom-control-label" for="customCheck{{ $lang->slug }}"></label>
							</div>
						</th>
						@php
							$data = json_decode($lang->langmeta->content,true);
						@endphp
						<td>{{ $data['lang_name'] }}</td>
						<td>{{ $data['lang_position'] }}</td>
						<td>{{ $lang->name }}</td>
						<td>
							<a href="{{ route('admin.lang.edit',['lang_code'=>$lang->slug,'theme_name'=>$lang->name]) }}" class="btn btn-info mr-2">{{ __('Customize') }}</a>
							<a href="{{ route('admin.lang.delete',['lang_code'=>$lang->slug,'theme_name'=>$lang->name]) }}" class="btn btn-danger cancel">{{ __('Delete') }}</a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</form>
	</div>
</div>
@endsection

@section('script')
<script src="{{ asset('admin/js/form.js') }}"></script>
<script type="text/javascript">
	"use strict";	
	//success response will assign this function
	function success(res){
		location.reload();
	}
	function errosresponse(xhr){

		$("#errors").html("<li class='text-danger'>"+xhr.responseJSON[0]+"</li>")
	}
</script>
@endsection