files/script/routes/web.php
	Route::get('/mysettings', 'Admin\UserController@index')->name('admin.admin.mysettings')->middleware('auth');
	Route::post('genup', 'Admin\UserController@genUpdate')->name('admin.users.genupdate')->middleware('auth');
	Route::post('passup', 'Admin\UserController@updatePassword')->name('admin.users.passup')->middleware('auth');

});


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| All Admin routes are here
|
*/

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => ['auth', 'admin']], function () {
	//dashboard route
	Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
	Route::get('static_data', 'DashboardController@static_data')->name('static_data');
	Route::get('dashboard/data/{period}', 'DashboardController@dashboardData')->name('dashboard.data');

	// role routes
	Route::resource('role', 'RoleController');
	Route::post('roles/destroy', 'RoleController@destroy')->name('roles.destroy');

	// users routes
	Route::resource('users', 'AdminController');
	Route::post('/userss/destroy', 'AdminController@destroy')->name('users.destroy');

	// page resource route
	Route::resource('page', 'PageController');
	Route::post('pages/destroy', 'PageController@destroy')->name('page.destroy');

	// blog resource route
	Route::resource('blog/post', 'PostController');
	Route::get('/blog/posts','PostController@index')->name('blog.all');
	Route::post('post/destroy', 'PostController@destroy')->name('post.destroys');
	Route::resource('blog/comment', 'CommentController');
	Route::get('/comment/disqus', 'CommentController@apiview')->name('dsiqus.settings');
	Route::post('blog/comments/destroy', 'CommentController@destroy')->name('comments.destroy');
	Route::get('blog/comments/reply/{id}', 'CommentController@reply')->name('comment.reply');

    // Disques Comment Route
	Route::post('disqus', 'CommentController@disqus')->name('disqus.store');

    // theme route
	Route::get('appearance/theme-options', 'ThemeoptionsController@index')->name('theme_option');

	// category route
	Route::post('categorys', 'CategoryController@destroy')->name('categorys.destroy');

	Route::resource('settings', 'SettingsController');
	// menu route
	Route::resource('appearance/menu', 'MenuController');
	Route::post('menues/destroy', 'MenuController@destroy')->name('menues.destroy');
	Route::post('menues/node', 'MenuController@MenuNodeStore')->name('menus.MenuNodeStore');

	//theme route
	Route::get('appearance/theme', 'ThemeController@index')->name('theme.index');
	Route::get('theme/{name}', 'ThemeController@active')->name('theme.active');
	Route::post('theme/upload', 'ThemeController@upload')->name('theme.upload');

	//widget route
	Route::get('appearance/widget', 'WidgetController@index')->name('widget.index');
	Route::get('appearance/bank/settings','WidgetController@bank_settings')->name('bank.settings');
	Route::post('appearance/bank/settings/update','WidgetController@bank_settings_update')->name('bank.settings.update');

	//themeoptions route
	Route::get('appearance/themeoptions', 'ThemeoptionsController@index')->name('themeoptions.index');

	//script route
	Route::resource('appearance/script', 'ScriptController');

	//Plugin route
	Route::get('plugin', 'PluginController@index')->name('plugin.index');
	Route::get('plugin/active/{plugin}', 'PluginController@active')->name('plugin.active');
	Route::get('plugin/deactive/{plugin}', 'PluginController@deactive')->name('plugin.deactive');
	Route::post('plugin/upload', 'PluginController@upload')->name('plugin.upload');

	//seo route
	Route::resource('setting/seo', 'SeoController');
	Route::get('setting/google-analytics', 'SettingsController@google_analytics')->name('google_analytics');
	Route::post('google_analytics_json', 'SettingsController@google_analytics_update')->name('google_analytics_service');

	//env route
	Route::resource('setting/env', 'EnvController');
	Route::resource('setting/filesystem', 'FilesystemController');

	//performance route
	Route::resource('setting/performance', 'PerfomaceController');

	//general route
	Route::resource('setting/general', 'GensettingsController');

	// permission route
	Route::get('permission', 'PermissionController@index')->name('permission.index');

	// usersystem route
	Route::get('usersystem', 'UsersystemController@index')->name('usersystem.index');

	// information route
	Route::get('information', 'InformationController@index')->name('information.index');

	//permissions Route
	Route::resource('permission', 'PermissionController');

	// Backup Route
	Route::get('backup','BackupController@index')->name('backup.index');
	Route::get('backup/store','BackupController@backup')->name('backup.store');
	Route::get('backup/delete/{file}','BackupController@delete')->name('backup.delete');
	Route::get('backup/download/{file}','BackupController@download')->name('backup.download');

	//langauge route
	Route::get('language','LanguageController@index')->name('language.index');
	Route::get('language/create','LanguageController@create')->name('language.create');
	Route::post('lang/store','LanguageController@store')->name('lang.store');
	Route::post('lang/set','LanguageController@set')->name('lang.set');
	Route::get('lang/{lang_code}/delete/{theme_name}','LanguageController@delete')->name('lang.delete');
	Route::get('lang/{lang_code}/edit/{theme_name}','LanguageController@edit')->name('lang.edit');
	Route::post('lang/{lang_code}/update/{theme_name}','LanguageController@update')->name('lang.update');

    // Media Routes
	Route::resource('media', 'MediaController');
	Route::get('medias/upload', 'MediaController@bulk_upload')->name('media.upload');
	Route::get('medias/json', 'MediaController@json')->name('medias.json');
	Route::get('media/info/{id}', 'MediaController@show');
	Route::post('medias/remove', 'MediaController@destroy')->name('medias.destroy');

	// Customizer All Route
	Route::get('customizer','CustomizerController@index')->name('customizer.index');
	Route::get('customizer/page_change','CustomizerController@page_change')->name('customizer.page_change');
	Route::get('customizer/section_option','CustomizerController@section_option')->name('customizer.section_option');
	Route::get('customizer/value_update','CustomizerController@value_update')->name('customizer.value_update');
	Route::get('customizer/multiple_settings_option','CustomizerController@multiple_settings_option')->name('customizer.multiple_settings_option');
	Route::post('customizer/image_upload','CustomizerController@image_upload')->name('customizer.image_upload');
	Route::get('customizer/save','CustomizerController@save')->name('customizer.save');
	Route::get('appearance/theme-options/settings','SettingsController@theme_settings')->name('theme.settings');
	Route::post('appearance/theme-options/settings-update','SettingsController@theme_settings_update')->name('theme.settings.update');

});


/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
|
| All Frontend routes are here
|
*/

Route::group(['namespace'=>'Amcoders\Theme\jomidar\http\controllers','middleware'=>'web'],function(){
	Route::get('/get_latest_property','DataController@get_latest_property')->name('latest.property');
	Route::get('/get_random_property','DataController@get_random_property')->name('random.property');
	Route::get('agents/data','DataController@agents')->name('agent.data');
	Route::get('recent_property/data','DataController@recent_property')->name('recent_property.data');
	Route::get('page_analytics','DataController@page_analytics');
	Route::get('city/data','DataController@city_data')->name('city.data');
	Route::get('blog/data','DataController@blog_data')->name('blog.data');
	Route::get('review/data','DataController@review')->name('review.data');
	Route::post('mailchamp','MailchampController@store')->name('mailchamp.store');
	Route::get('property/{slug}','PropertyController@show')->name('property.show');
	Route::get('project/{slug}','PropertyController@project_view');
	Route::get('list','PropertyController@list')->name('list');
	Route::get('project','PropertyController@project');
	Route::get('map','PropertyController@map')->name('map');
	Route::get('state/{slug}','PropertyController@city');
	Route::get('get_properties','DataController@get_properties');
	Route::get('get_projects','DataController@get_projects');
	Route::get('reviews','PropertyController@reviews')->name('reviews.data');
	Route::post('review/store','PropertyController@review_store')->name('review.store');
	Route::post('property/inquiryform','PropertyController@inquiryform')->name('property.inquiryform');
	Route::post('mortgage/calculator','PropertyController@calculator')->name('mortgage.calculator');
	Route::get('agent/{slug}/show','AgentshowController@show')->name('agent.show');
	Route::get('agent/property/list/{slug}','AgentshowController@property_get')->name('agent.property');
	Route::get('agent/property/review/get','AgentshowController@review_get')->name('agent.reviews.data');
	Route::get('agency/{slug}/show','AgencyController@show')->name('agency.show');
	Route::get('agency/agent/list','AgencyController@agent_list')->name('agency.agent.list');
	Route::get('agency/property/list','AgencyController@property_list')->name('agency.property.list');
	Route::get('agency/review/list','AgencyController@review_list')->name('agency.review.list');
	Route::get('agent/list','AgentController@list')->name('agent.list');
	Route::get('agent/list/data','AgentController@agents_data')->name('agent.list.data');
	Route::get('agency/list','AgencyController@list')->name('agency.list');
	Route::get('agency/list/data','AgencyController@agency_data')->name('agency.list.data');
	Route::post('property/favourite/request','PropertyController@favourite')->name('property.favourite');

files/script/app/Http/Controllers/Admin/PluginController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use ZipArchive;


class PluginController extends Controller
{
	public function index()
	{
		$file = file_get_contents(base_path().'/am-content/Plugins/plugin.json');
		$plugins = json_decode($file, true);
		return view('admin.plugin.index',compact('plugins'));
	}

	public function active($plugin)
	{
    	// read file
		$data = file_get_contents(base_path().'/am-content/Plugins/plugin.json');

		// decode json to array
		$json_arr = json_decode($data, true);

		foreach ($json_arr as $key => $value) {
			if ($value['Text Domain'] == $plugin) {
				$json_arr[$key]['status'] = "active";
			}
		}

		// encode array to json and save to file
		file_put_contents(base_path().'/am-content/Plugins/plugin.json', json_encode($json_arr,JSON_PRETTY_PRINT));

		return back();
	}

	public function deactive($plugin)
	{
    	// read file
		$data = file_get_contents(base_path().'/am-content/Plugins/plugin.json');

		// decode json to array
		$json_arr = json_decode($data, true);

		foreach ($json_arr as $key => $value) {
			if ($value['Text Domain'] == $plugin) {
				$json_arr[$key]['status'] = "deactive";
			}
		}

		// encode array to json and save to file
		file_put_contents(base_path().'/am-content/Plugins/plugin.json', json_encode($json_arr,JSON_PRETTY_PRINT));

		return back();
	}


	public function upload(Request $request)
	{
		return back();
		$uploadedFile = $request->file('file');
		if (isset($uploadedFile)) {
			$filename = $uploadedFile->getClientOriginalName();

			$name = substr($filename, 0, -4);
			$path = base_path().'/am-content/Plugins/';

			$uploadedFile->move($path, $filename);
			$zip = new ZipArchive;
			$res = $zip->open(base_path().'/am-content/Plugins/'.$filename);
			if ($res === TRUE) {
				$zip->extractTo(base_path().'/am-content/Plugins/');
				$zip->close();
				unlink(base_path().'/am-content/Plugins/'.$filename);

				$inp = file_get_contents( base_path().'/am-content/Plugins/plugin.json');
				$tempArray = json_decode($inp,true);


				if (file_exists(base_path().'/am-content/Plugins/'.$name.'/single_plugin.json')) {
					$files = file_get_contents( base_path().'/am-content/Plugins/'.$name.'/single_plugin.json');
				}else{
					return back()->with('status','You plugin has many problem');
				}

				$data = json_decode($files, true);


				foreach ($tempArray as $key => $value) {
					if ($value['Text Domain'] == $data['Text Domain']) {
						return back()->with('status','This Plugin is already exists');
					}
				}

				$tempArray[] = $data;
				$final_data = json_encode($tempArray);


				file_put_contents(base_path().'/am-content/Plugins/plugin.json', $final_data);



				//helper function append
				$inps = file_get_contents( base_path().'/am-content/Plugins/Helper.json');
				$tempArrays = json_decode($inps,true);


				if (file_exists(base_path().'/am-content/Plugins/'.$name.'/single_helper.json')) {
					$get_file = file_get_contents( base_path().'/am-content/Plugins/'.$name.'/single_helper.json');
				}else{
					return back()->with('status','You plugin has many problem');
				}

				$datas = json_decode($get_file, true);

				$tempArrays[] = $datas;
				$final_datas = json_encode($tempArrays);


				file_put_contents(base_path().'/am-content/Plugins/helper.json', $final_datas);

				return back();

			}
		}
	}
}

files/script/resources/views/admin/plugin/index.blade.php
@extends('layouts.backend.app')

@section('content')
<div class="card"  >
    <div class="card-body">
        <div class="row mb-30">
            <div class="col-lg-6">
                <h4>{{ __('Plugin List') }}</h4>
            </div>
            <div class="col-lg-6">
                <div class="add-new-btn">

                </div>
            </div>
        </div>
        <div class="table-responsive custom-table">
            <table class="table">
                <thead>
                    <tr>
                        <th class="am-title">{{ __('Plugin') }}</th>
                        <th class="am-title">{{ __('Description') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($plugins as $plugin)
                    <tr>
                        <td>{{ $plugin['Plugin Name'] }}
                            <div class="hover">
                                @if($plugin['status'] == 'deactive')
                                <a class="last" href="{{ route('admin.plugin.active',$plugin['Text Domain']) }}">{{ __('Active') }}</a>
                                @else
                                <a class="last" href="{{ route('admin.plugin.deactive',$plugin['Text Domain']) }}">{{ __('Deactive') }}</a>
                                @endif
                            </div>
                        </td>
                        <td>
                            <div class="plugin-des">
                                <p>{{ $plugin['Description'] }}</p>
                            </div>
                            <div class="plugin-anthor-info d-flex">
                                <span><strong>{{ __('Version') }}:</strong>{{ $plugin['Version'] }}</span>
                                <span class="last"><strong>{{ __('By') }}</strong><a target="_blank" href="{{ $plugin['Author URI'] }}">{{ $plugin['Author'] }}</a></span>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th class="am-title">{{ __('Plugin') }}</th>
                        <th class="am-title">{{ __('Description') }}</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="new_plugin" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">{{ __('Upload Plugin') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('admin.plugin.upload') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="modal-body mt-35 mb-35">
                    <div class="custom-form">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="file" id="theme_file">
                            <label class="custom-file-label" for="theme_file">{{ __('Choose file') }}</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn">{{ __('Install Now') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection